### ISSUE TITLE
get-transaction-pool-hashes.bin throws an error

### ISSUE THREAD

**Issue by marceloneil** [glv2/cl-monero-tools#1]
The endpoint for this function returns an improperly formatted JSON response, so naturally the command fails at parsing the response. (My node: http://xmr.1lab.me/get_transaction_pool_hashes.bin)

```
* (monero-tools-rpc:get-transaction-pool-hashes.bin)

debugger invoked on a JSON:JSON-SYNTAX-ERROR in thread
#<THREAD "main thread" RUNNING {10005505B3}>:
  Invalid JSON character escape sequence: \v [in #<SB-IMPL::STRING-INPUT-STREAM {1005D44D53}> at position 181]
```

**Comment by glv2** [comment]
Yes, I think the *get-transaction-pool* call can return invalid JSON too. I think I'll add some special processing for these calls.

A non binary *get-transaction-pool-hashes* RPC was added because of this problem; it's in the master branch of the monero code and not yet in a release.

**Comment by marceloneil** [comment]
Oh great, thanks!

I didn't know that there was a new endpoint being added, that's great. It seems odd that they didn't use the binary storage format to begin with though

**Comment by glv2** [comment]
I added some special post-processing to deal with the invalid JSON that can be returned by the *get-transaction-pool*, *get-transaction-pool-hashes.bin* and *get-transaction-pool-stats* RPCs in commit b10058be1e128ec5202c836e5ba289fac9eaa99f.

**Comment by marceloneil** [comment]
It seems to work, thanks!
