### ISSUE TITLE
ring-size is not always accurate

### ISSUE THREAD

**Issue by marceloneil** [glv2/cl-monero-tools#2]
https://github.com/glv2/cl-monero-tools/blob/99763bd569fdaa37eb0cc58f73158b0eb2d256fd/src/serialization/deserialization.lisp#L356-L358
It doesn't seem safe to assume that the `ring-size` of each input is identical to the first input, for example key image 18 of [this transaction](https://moneroexplorer.com/tx/7ccdb8992b73d5fa9b284fef2387a4c8d599dc743685041093194be8187d3787/1) has 5 ring members, rather than key image 01 which has 6 ring members.

**Comment by marceloneil** [comment]
I'm guessing the best method is to create an array of ring-sizes, but I'm not sure

**Comment by glv2** [comment]
Indeed.

I pushed a fix for this bug (commit f9d4c1d8fac8bbb7be22c0257ae548159b814f2a).
I tested it quickly on the transaction you mentioned and it seems to work, but tell me if you still see a problem.

**Comment by marceloneil** [comment]
Works great, thanks!
