### ISSUE TITLE
Handling invalid extra fields

### ISSUE THREAD

**Issue by marceloneil** [glv2/cl-monero-tools#3]
It seems that [this transaction](https://moneroexplorer.com/search?value=e87c675a85f34ecac58a8846613d25062f1813e1023c552b705afad32b972c38), (and possibly other ones) have some invalid "extra" fields. In this case, the `additional-public-keys` key `4` is followed by a key rather than a vector

**Comment by glv2** [comment]
I added some size checks that should catch this kind of malformed extra fields (commit d23146277e0d1cb7d4acebca34e7fe3f19678871).
